export const fieldAliases: Record<string, string[]> = {
  title: ["title"],
  authors: ["authors", "author"],
  abstract: ["abstract"],
  doi: ["doi"],
  journal: ["journal"],
  volume: ["volume"],
  issue: ["issue"],
  pages: ["pages", "page"],
  keywords: ["keywords", "keyword"],
  publisher: ["publisher"],
  year: ["year"],
  publisheddate: ["publisheddate", "publicationdate", "date"],
  issn: ["issn"],
  eissn: ["eissn"],
  language: ["language"],
  md5: ["md5", "md5hash"],
  conferencename: ["conferencename", "conference"],
  conferencelocation: ["conferencelocation", "location"],
  conferencecountry: ["conferencecountry", "country"],
  conferenceyear: ["conferenceyear", "confyear"],
};
