import type { AuditLogEntry, AuditLogActionType, AuditLogStatus } from "../../../types/auditLog";

const baseTime = new Date();

const createTimestamp = (daysAgo: number, hoursAgo = 0, minutesAgo = 0): string => {
  const date = new Date(baseTime);
  date.setDate(date.getDate() - daysAgo);
  date.setHours(date.getHours() - hoursAgo);
  date.setMinutes(date.getMinutes() - minutesAgo);
  return date.toISOString();
};

interface LogSeed {
  daysAgo: number;
  hoursAgo?: number;
  minutesAgo?: number;
  user: string;
  action: string;
  actionType: AuditLogActionType;
  resourceType: string;
  resourceId: string;
  status: AuditLogStatus;
  ipAddress: string;
  userAgent: string;
  importance?: "normal" | "high";
  oldValue: Record<string, unknown> | null;
  newValue: Record<string, unknown> | null;
}

const createLog = (seed: LogSeed): AuditLogEntry => ({
  id: `${seed.actionType}-${seed.resourceId}-${seed.daysAgo}-${seed.hoursAgo ?? 0}`,
  timestamp: createTimestamp(seed.daysAgo, seed.hoursAgo, seed.minutesAgo),
  user: seed.user,
  action: seed.action,
  actionType: seed.actionType,
  resourceType: seed.resourceType,
  resourceId: seed.resourceId,
  status: seed.status,
  ipAddress: seed.ipAddress,
  userAgent: seed.userAgent,
  importance: seed.importance ?? "normal",
  oldValue: seed.oldValue,
  newValue: seed.newValue,
});

export const auditLogMockData: AuditLogEntry[] = [
  createLog({
    daysAgo: 0,
    hoursAgo: 1,
    user: "Dr. Alicia Morgan",
    action: "Exported audit log bundle",
    actionType: "export",
    resourceType: "Audit Log",
    resourceId: "AUD-2026-0415",
    status: "Success",
    ipAddress: "172.16.1.24",
    userAgent: "Chrome 124 / macOS 14.4",
    importance: "high",
    oldValue: null,
    newValue: {
      format: "CSV",
      records: 42,
      scope: "Last 7 days",
    },
  }),
  createLog({
    daysAgo: 0,
    hoursAgo: 4,
    user: "Marcus Chen",
    action: "Updated review protocol",
    actionType: "update",
    resourceType: "Protocol",
    resourceId: "PROT-118",
    status: "Success",
    ipAddress: "172.16.1.31",
    userAgent: "Firefox 126 / Windows 11",
    oldValue: { status: "Draft", version: 5 },
    newValue: { status: "Approved", version: 6 },
  }),
  createLog({
    daysAgo: 0,
    hoursAgo: 5,
    minutesAgo: 12,
    user: "System Scheduler",
    action: "Auto-synced search source",
    actionType: "system",
    resourceType: "Search Source",
    resourceId: "SRC-RT-09",
    status: "Success",
    ipAddress: "127.0.0.1",
    userAgent: "Background Worker / v2.8.1",
    oldValue: { lastSyncStatus: "Queued" },
    newValue: { lastSyncStatus: "Completed", documentCount: 12840 },
  }),
  createLog({
    daysAgo: 1,
    hoursAgo: 2,
    user: "Nora Patel",
    action: "Deleted duplicate paper",
    actionType: "delete",
    resourceType: "Paper",
    resourceId: "PPR-8841",
    status: "Success",
    ipAddress: "172.16.1.18",
    userAgent: "Safari 17 / iPadOS 17",
    importance: "high",
    oldValue: { title: "Machine learning in healthcare", duplicateOf: "PPR-5411" },
    newValue: { archived: true, removedFromQueue: true },
  }),
  createLog({
    daysAgo: 1,
    hoursAgo: 5,
    user: "Priya Shah",
    action: "Marked paper as not retrieved",
    actionType: "update",
    resourceType: "Paper",
    resourceId: "PPR-6520",
    status: "Success",
    ipAddress: "172.16.1.45",
    userAgent: "Chrome 125 / Windows 11",
    oldValue: { retrievalStatus: "Pending" },
    newValue: { retrievalStatus: "Not retrieved" },
  }),
  createLog({
    daysAgo: 1,
    hoursAgo: 8,
    user: "Dr. Alicia Morgan",
    action: "Reviewed screening conflict",
    actionType: "review",
    resourceType: "Conflict",
    resourceId: "CFL-221",
    status: "Success",
    ipAddress: "172.16.1.24",
    userAgent: "Chrome 124 / macOS 14.4",
    oldValue: { decision: "Unresolved" },
    newValue: { decision: "Resolved", outcome: "Exclude" },
  }),
  createLog({
    daysAgo: 2,
    hoursAgo: 2,
    user: "Luis Fernandez",
    action: "Created new project workspace",
    actionType: "create",
    resourceType: "Project",
    resourceId: "PRJ-204",
    status: "Success",
    ipAddress: "172.16.1.52",
    userAgent: "Edge 126 / Windows 11",
    oldValue: null,
    newValue: { title: "Diabetes review 2026", status: "Draft", members: 6 },
  }),
  createLog({
    daysAgo: 2,
    hoursAgo: 6,
    user: "Emma Davis",
    action: "Updated user role",
    actionType: "update",
    resourceType: "User",
    resourceId: "USR-113",
    status: "Success",
    ipAddress: "172.16.1.61",
    userAgent: "Chrome 125 / macOS 14.4",
    oldValue: { role: "Reviewer" },
    newValue: { role: "Project Lead" },
  }),
  createLog({
    daysAgo: 2,
    hoursAgo: 14,
    user: "System Scheduler",
    action: "Reindexed audit archive",
    actionType: "system",
    resourceType: "Audit Store",
    resourceId: "ARC-2026-Q2",
    status: "Success",
    ipAddress: "127.0.0.1",
    userAgent: "Background Worker / v2.8.1",
    oldValue: { indexedRecords: 12451 },
    newValue: { indexedRecords: 12489 },
  }),
  createLog({
    daysAgo: 3,
    hoursAgo: 1,
    user: "Olivia Kim",
    action: "Failed export due to missing scope",
    actionType: "export",
    resourceType: "Audit Log",
    resourceId: "AUD-2026-0412",
    status: "Failed",
    ipAddress: "172.16.1.30",
    userAgent: "Chrome 124 / macOS 14.4",
    importance: "high",
    oldValue: { format: "XLSX", scope: null },
    newValue: { format: "XLSX", scope: "Invalid date range" },
  }),
  createLog({
    daysAgo: 3,
    hoursAgo: 4,
    user: "Marcus Chen",
    action: "Added search source",
    actionType: "create",
    resourceType: "Search Source",
    resourceId: "SRC-PUBMED",
    status: "Success",
    ipAddress: "172.16.1.31",
    userAgent: "Firefox 126 / Windows 11",
    oldValue: null,
    newValue: { name: "PubMed", enabled: true },
  }),
  createLog({
    daysAgo: 4,
    hoursAgo: 2,
    user: "Nora Patel",
    action: "Deleted stale import batch",
    actionType: "delete",
    resourceType: "Import Batch",
    resourceId: "IMP-741",
    status: "Success",
    ipAddress: "172.16.1.18",
    userAgent: "Safari 17 / iPadOS 17",
    importance: "high",
    oldValue: { batchName: "March review cleanup", records: 210 },
    newValue: { archived: true },
  }),
  createLog({
    daysAgo: 4,
    hoursAgo: 7,
    user: "Priya Shah",
    action: "Updated extraction threshold",
    actionType: "update",
    resourceType: "System Setting",
    resourceId: "SET-EXTRACT-THRESHOLD",
    status: "Success",
    ipAddress: "172.16.1.45",
    userAgent: "Chrome 125 / Windows 11",
    oldValue: { threshold: 0.73 },
    newValue: { threshold: 0.81 },
  }),
  createLog({
    daysAgo: 5,
    hoursAgo: 3,
    user: "Emma Davis",
    action: "Viewed restricted paper details",
    actionType: "access",
    resourceType: "Paper",
    resourceId: "PPR-9904",
    status: "Success",
    ipAddress: "172.16.1.61",
    userAgent: "Chrome 125 / macOS 14.4",
    oldValue: { visibility: "Restricted" },
    newValue: { visibility: "Restricted" },
  }),
  createLog({
    daysAgo: 6,
    hoursAgo: 1,
    user: "Luis Fernandez",
    action: "Updated project members",
    actionType: "update",
    resourceType: "Project",
    resourceId: "PRJ-188",
    status: "Success",
    ipAddress: "172.16.1.52",
    userAgent: "Edge 126 / Windows 11",
    oldValue: { members: 4 },
    newValue: { members: 7 },
  }),
  createLog({
    daysAgo: 7,
    hoursAgo: 9,
    user: "Dr. Alicia Morgan",
    action: "Exported screening summary",
    actionType: "export",
    resourceType: "Screening Report",
    resourceId: "SCR-742",
    status: "Success",
    ipAddress: "172.16.1.24",
    userAgent: "Chrome 124 / macOS 14.4",
    importance: "high",
    oldValue: null,
    newValue: { format: "JSON", records: 219 },
  }),
  createLog({
    daysAgo: 8,
    hoursAgo: 4,
    user: "Olivia Kim",
    action: "Login attempt rejected",
    actionType: "access",
    resourceType: "Session",
    resourceId: "SES-4471",
    status: "Failed",
    ipAddress: "192.168.0.89",
    userAgent: "Safari 17 / iPadOS 17",
    oldValue: { attempts: 3 },
    newValue: { attempts: 4, locked: true },
  }),
  createLog({
    daysAgo: 9,
    hoursAgo: 2,
    user: "System Scheduler",
    action: "Generated nightly digest",
    actionType: "system",
    resourceType: "Digest Job",
    resourceId: "JOB-DIGEST-NIGHTLY",
    status: "Success",
    ipAddress: "127.0.0.1",
    userAgent: "Background Worker / v2.8.1",
    oldValue: { lastRun: "2026-04-05T01:00:00.000Z" },
    newValue: { lastRun: createTimestamp(9, 2), items: 17 },
  }),
  createLog({
    daysAgo: 10,
    hoursAgo: 6,
    user: "Marcus Chen",
    action: "Deleted project note",
    actionType: "delete",
    resourceType: "Note",
    resourceId: "NOTE-233",
    status: "Failed",
    ipAddress: "172.16.1.31",
    userAgent: "Firefox 126 / Windows 11",
    importance: "high",
    oldValue: { content: "Draft protocol note" },
    newValue: { error: "Insufficient permissions" },
  }),
  createLog({
    daysAgo: 11,
    hoursAgo: 1,
    user: "Priya Shah",
    action: "Updated review status",
    actionType: "update",
    resourceType: "Review",
    resourceId: "REV-514",
    status: "Success",
    ipAddress: "172.16.1.45",
    userAgent: "Chrome 125 / Windows 11",
    oldValue: { status: "In progress" },
    newValue: { status: "Completed" },
  }),
  createLog({
    daysAgo: 12,
    hoursAgo: 3,
    user: "Emma Davis",
    action: "Opened admin audit log",
    actionType: "access",
    resourceType: "Audit Log",
    resourceId: "AUD-ENTRY-OPEN",
    status: "Success",
    ipAddress: "172.16.1.61",
    userAgent: "Chrome 125 / macOS 14.4",
    oldValue: { screen: "Overview" },
    newValue: { screen: "Audit Logs" },
  }),
];
