// import { FieldTypeEnum, type ExtractionTemplateDto } from "../../../types/dataExtraction";
// import {
//   PaperSelectionStatus,
//   ScreeningDecisionType,
//   type PaperWithDecisionsResponse,
// } from "../../../types/studySelection";
// import type { ExtractionPaperRecord } from "./types";

// const MOCK_PROTOCOL_ID = "mock-protocol-data-extraction";
// const MOCK_TEMPLATE_ID = "mock-template-har-study";
// const NOW = "2026-03-13T09:00:00.000Z";

// function createMockPaper(
//   paperId: string,
//   title: string,
//   paperStatus: PaperSelectionStatus,
//   statusText: string,
//   overrides?: Partial<PaperWithDecisionsResponse>,
// ): PaperWithDecisionsResponse {
//   return {
//     paperId,
//     title,
//     doi: null,
//     authors: "Nguyen A.; Tran B.",
//     publicationYear: 2024,
//     abstract:
//       "This is a mock abstract used for Data Extraction conducting workspace testing before backend API is available.",
//     journal: "Journal of Software Evidence",
//     source: "Scopus",
//     keywords: "systematic review; extraction; evidence synthesis",
//     publicationType: "Journal",
//     volume: "18",
//     issue: "2",
//     pages: "101-120",
//     publisher: "Mock Publisher",
//     language: "English",
//     url: "https://example.org/mock-study",
//     pdfUrl: "https://example.org/mock-study.pdf",
//     pdfFileName: null,
//     conferenceName: null,
//     conferenceLocation: null,
//     journalIssn: "1234-5678",
//     status: paperStatus,
//     statusText,
//     finalDecision: null,
//     finalDecisionText: null,
//     decisions: [],
//     resolution: null,
//     ...overrides,
//   };
// }

// export const MOCK_PAPERS_WITH_DECISIONS: PaperWithDecisionsResponse[] = [
//   // ── Included papers ────────────────────────────────────────────────────────
//   createMockPaper(
//     "paper-001",
//     "AI-supported Study Screening for Systematic Literature Reviews",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Le Q.; Vo M.; Nguyen H.",
//       publicationYear: 2022,
//       source: "IEEE Xplore",
//       abstract:
//         "This study investigates how artificial intelligence, particularly NLP-based classifiers, can augment the title-and-abstract screening phase in systematic literature reviews (SLR). A within-subjects experiment with 12 reviewers compared AI-assisted versus manual screening across three topic areas. AI assistance reduced screening time by 42% while maintaining a recall above 0.97. Human reviewers intervened on 18% of AI decisions. The results suggest that semi-automated screening tools can substantially accelerate SLR workflows without sacrificing sensitivity.",
//     },
//   ),
//   createMockPaper(
//     "paper-002",
//     "Controlled Experiment on Data Extraction Reliability in Evidence Synthesis",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Pham T.; Hoang N.; Dang K.",
//       publicationYear: 2021,
//       source: "ACM Digital Library",
//       abstract:
//         "Data extraction is a labor-intensive and error-prone step in systematic reviews. This randomized controlled trial enrolled 48 reviewers randomly assigned to tool-assisted or unaided extraction conditions. Inter-rater reliability was measured using Cohen's kappa on 14 extraction fields. The tool-assisted group showed significantly higher kappa values (0.84 vs 0.61, p < 0.001) and 31% fewer critical extraction errors. Results indicate that structured extraction forms embedded in collaborative tools can reliably improve evidence quality.",
//     },
//   ),
//   createMockPaper(
//     "paper-003",
//     "Resolving Reviewer Disagreement in Evidence Synthesis: A Framework Study",
//     PaperSelectionStatus.Resolved,
//     "Resolved",
//     {
//       authors: "Tran B.; Ly C.; Bui A.",
//       publicationYear: 2020,
//       source: "Scopus",
//       abstract:
//         "Reviewer disagreement is an inherent challenge in dual-reviewer systematic review designs. This paper presents a structured consensus framework combining automated conflict detection with adjudication workflows. Evaluated across five SLR projects totalling 320 papers, the framework reduced unresolved conflicts by 68% and decreased average resolution time from 4.2 days to 1.1 days. The framework is independent of domain and integrates with existing SLR tooling via a REST API surface.",
//       resolution: {
//         id: "resolution-003",
//         studySelectionProcessId: "mock-screening",
//         paperId: "paper-003",
//         paperTitle: "Resolving Reviewer Disagreement in Evidence Synthesis: A Framework Study",
//         finalDecision: ScreeningDecisionType.Include,
//         finalDecisionText: "Include",
//         resolutionNotes: "Included after adjudicator review.",
//         resolvedBy: "resolver-1",
//         resolverName: "Lead Reviewer",
//         resolvedAt: NOW,
//       },
//     },
//   ),
//   createMockPaper(
//     "paper-006",
//     "Machine Learning for Automated Evidence Grading in Meta-Analysis",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Dao P.; Nguyen V.; Tran T.",
//       publicationYear: 2023,
//       source: "PubMed",
//       abstract:
//         "Traditional evidence grading in systematic reviews relies on subjective expert judgment and is slow at scale. This study proposes a machine-learning pipeline that automates GRADE evidence rating across four certainty domains. Using a cross-validated dataset of 920 previously graded studies, the model achieved 79% agreement with expert raters on overall certainty and 84% on individual sub-domains. The approach reduces evidence grading time while surfacing uncertainty scores that help focus expert effort on low-confidence cases.",
//     },
//   ),
//   createMockPaper(
//     "paper-007",
//     "Quality Assessment Automation for Systematic Reviews Using BERT",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Huynh L.; Vu T.",
//       publicationYear: 2022,
//       source: "Web of Science",
//       abstract:
//         "Risk-of-bias assessment is a critical but time-consuming quality appraisal step in systematic reviews. We fine-tuned BERT on 560 annotated studies to predict Cochrane RoB 2.0 domain judgments. The model reached a macro-F1 of 0.73 on a held-out test set and correctly flagged high-risk items in 88% of cases. Integration with an SLR workflow tool shortened per-study quality appraisal from 47 minutes to 11 minutes on average, representing a 77% time saving.",
//     },
//   ),
//   createMockPaper(
//     "paper-008",
//     "Human Factors and Usability of Systematic Review Support Tools",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Mai H.; Le D.; Nguyen Q.",
//       publicationYear: 2021,
//       source: "ACM Digital Library",
//       abstract:
//         "Despite the proliferation of software tools supporting systematic reviews, adoption rates among researchers remain low. This mixed-methods study surveyed 142 reviewers and conducted 18 think-aloud sessions to identify usability barriers in five popular SLR tools. Key findings indicate that steep learning curves, lack of real-time collaboration, and inconsistent data export formats are the leading obstacles to adoption. A prototype addressing these issues achieved a System Usability Scale score of 82.4, significantly outperforming the existing tools evaluated.",
//     },
//   ),
//   createMockPaper(
//     "paper-009",
//     "Bias Detection in Multi-Database Literature Search Strategies",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Cao M.; Dinh T.; Phan N.",
//       publicationYear: 2023,
//       source: "Embase",
//       abstract:
//         "Publication bias and database selection bias can distort meta-analytic conclusions in systematic reviews. This study applied funnel plot analysis, Egger's test, and a novel overlap coefficient metric across 34 published SLRs to quantify how multi-database coverage affected bias risk. Reviews that searched four or more databases showed 23% lower bias risk scores than single-database reviews. A simulation study further demonstrates that omitting gray literature doubles the probability of a positive-result bias. Practical database selection guidelines are provided.",
//     },
//   ),
//   createMockPaper(
//     "paper-010",
//     "Collaborative Data Extraction Platforms: A Comparative Evaluation",
//     PaperSelectionStatus.Included,
//     "Included",
//     {
//       authors: "Vo K.; Trinh L.; Luong A.",
//       publicationYear: 2020,
//       source: "IEEE Xplore",
//       abstract:
//         "Collaborative extraction environments in which multiple reviewers annotate the same study in parallel are increasingly common, yet no head-to-head comparison of platforms exists. We recruited 60 doctoral students to perform full data extraction on 30 included studies across Covidence, Rayyan, and a custom-built platform. Extraction accuracy was highest on the custom platform (kappa = 0.89) and lowest on Covidence (kappa = 0.74). Conflict-detection responsiveness and field-level guidance were the strongest predictors of accuracy. Open-design implications for review tooling are discussed.",
//     },
//   ),
//   createMockPaper(
//     "paper-011",
//     "The Impact of Extraction Form Design on Reviewer Agreement",
//     PaperSelectionStatus.Resolved,
//     "Resolved",
//     {
//       authors: "Nguyen T.; Bui P.",
//       publicationYear: 2019,
//       source: "Cochrane Library",
//       abstract:
//         "Despite extensive guidance on extraction form content, little is known about how form design — field ordering, instruction wording, and option granularity — affects reviewer agreement. A randomized experiment with 80 trained reviewers compared three form variants across 40 studies in a completed SLR. The high-guidance form variant produced significantly better inter-rater agreement (kappa = 0.87) compared to the minimal variant (kappa = 0.61). Instruction quality at the field level explained 38% of variance in reviewer disagreement. Recommendations for form authoring are provided.",
//       resolution: {
//         id: "resolution-011",
//         studySelectionProcessId: "mock-screening",
//         paperId: "paper-011",
//         paperTitle: "The Impact of Extraction Form Design on Reviewer Agreement",
//         finalDecision: ScreeningDecisionType.Include,
//         finalDecisionText: "Include",
//         resolutionNotes: "Included after lead reviewer adjudication.",
//         resolvedBy: "resolver-1",
//         resolverName: "Lead Reviewer",
//         resolvedAt: NOW,
//       },
//     },
//   ),
//   // ── Excluded / Pending (should NOT appear in the extraction queue) ──────────
//   createMockPaper(
//     "paper-004",
//     "Out-of-scope Study on General Web Scraping",
//     PaperSelectionStatus.Excluded,
//     "Excluded",
//   ),
//   createMockPaper(
//     "paper-005",
//     "Preprint Pending Full Screening Decision",
//     PaperSelectionStatus.Pending,
//     "Pending",
//   ),
// ];

// export const MOCK_EXTRACTION_TEMPLATES: ExtractionTemplateDto[] = [
//   {
//     templateId: MOCK_TEMPLATE_ID,
//     protocolId: MOCK_PROTOCOL_ID,
//     name: "HAR Study Data Extraction Form (Mock)",
//     description: "Mock template for conducting phase UI testing.",
//     fields: [
//       {
//         fieldId: "field_study_characteristics",
//         templateId: MOCK_TEMPLATE_ID,
//         parentFieldId: undefined,
//         name: "Study Characteristics",
//         instruction: "General descriptors of the included study",
//         fieldType: FieldTypeEnum.Text,
//         isRequired: false,
//         orderIndex: 1,
//         options: [],
//         subFields: [
//           {
//             fieldId: "field_sample_size",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_study_characteristics",
//             name: "Sample Size",
//             instruction: "Total participants in the study",
//             fieldType: FieldTypeEnum.Integer,
//             isRequired: true,
//             orderIndex: 1,
//             options: [],
//             subFields: [],
//           },
//           {
//             fieldId: "field_study_design",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_study_characteristics",
//             name: "Study Design",
//             instruction: "Choose the primary design",
//             fieldType: FieldTypeEnum.SingleSelect,
//             isRequired: true,
//             orderIndex: 2,
//             options: [
//               { optionId: "opt-design-rct", fieldId: "field_study_design", value: "RCT", displayOrder: 1 },
//               { optionId: "opt-design-cohort", fieldId: "field_study_design", value: "Cohort", displayOrder: 2 },
//               { optionId: "opt-design-case-control", fieldId: "field_study_design", value: "Case-Control", displayOrder: 3 },
//             ],
//             subFields: [],
//           },
//           {
//             fieldId: "field_followup_months",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_study_characteristics",
//             name: "Follow-up (months)",
//             instruction: "Duration of follow-up period",
//             fieldType: FieldTypeEnum.Decimal,
//             isRequired: false,
//             orderIndex: 3,
//             options: [],
//             subFields: [],
//           },
//         ],
//       },
//       {
//         fieldId: "field_baseline",
//         templateId: MOCK_TEMPLATE_ID,
//         parentFieldId: undefined,
//         name: "Participant Baseline",
//         instruction: "Baseline demographic characteristics",
//         fieldType: FieldTypeEnum.Text,
//         isRequired: false,
//         orderIndex: 2,
//         options: [],
//         subFields: [
//           {
//             fieldId: "field_age_mean",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_baseline",
//             name: "Mean Age",
//             instruction: "Average participant age",
//             fieldType: FieldTypeEnum.Decimal,
//             isRequired: false,
//             orderIndex: 1,
//             options: [],
//             subFields: [],
//           },
//           {
//             fieldId: "field_female_percent",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_baseline",
//             name: "Female (%)",
//             instruction: "Percentage of female participants",
//             fieldType: FieldTypeEnum.Decimal,
//             isRequired: false,
//             orderIndex: 2,
//             options: [],
//             subFields: [],
//           },
//         ],
//       },
//       {
//         fieldId: "field_intervention_group",
//         templateId: MOCK_TEMPLATE_ID,
//         parentFieldId: undefined,
//         name: "Intervention",
//         instruction: "Intervention descriptors",
//         fieldType: FieldTypeEnum.Text,
//         isRequired: false,
//         orderIndex: 3,
//         options: [],
//         subFields: [
//           {
//             fieldId: "field_intervention_type",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_intervention_group",
//             name: "Intervention Type",
//             instruction: "Pick one type",
//             fieldType: FieldTypeEnum.SingleSelect,
//             isRequired: true,
//             orderIndex: 1,
//             options: [
//               { optionId: "opt-int-software", fieldId: "field_intervention_type", value: "Software Tool", displayOrder: 1 },
//               { optionId: "opt-int-training", fieldId: "field_intervention_type", value: "Training Program", displayOrder: 2 },
//               { optionId: "opt-int-process", fieldId: "field_intervention_type", value: "Process Change", displayOrder: 3 },
//             ],
//             subFields: [],
//           },
//           {
//             fieldId: "field_dosage_description",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_intervention_group",
//             name: "Dosage / Intensity",
//             instruction: "Describe intervention intensity or duration",
//             fieldType: FieldTypeEnum.Text,
//             isRequired: false,
//             orderIndex: 2,
//             options: [],
//             subFields: [],
//           },
//         ],
//       },
//       {
//         fieldId: "field_outcomes_group",
//         templateId: MOCK_TEMPLATE_ID,
//         parentFieldId: undefined,
//         name: "Outcomes",
//         instruction: "Result extraction",
//         fieldType: FieldTypeEnum.Text,
//         isRequired: false,
//         orderIndex: 4,
//         options: [],
//         subFields: [
//           {
//             fieldId: "field_primary_outcome",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_outcomes_group",
//             name: "Primary Outcome",
//             instruction: "Main outcome text",
//             fieldType: FieldTypeEnum.Text,
//             isRequired: true,
//             orderIndex: 1,
//             options: [],
//             subFields: [],
//           },
//           {
//             fieldId: "field_adverse_events",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_outcomes_group",
//             name: "Adverse Events Reported",
//             instruction: "Whether adverse events were reported",
//             fieldType: FieldTypeEnum.Boolean,
//             isRequired: false,
//             orderIndex: 2,
//             options: [],
//             subFields: [],
//           },
//           {
//             fieldId: "field_risk_of_bias",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_outcomes_group",
//             name: "Risk of Bias",
//             instruction: "Select reviewer judgment",
//             fieldType: FieldTypeEnum.SingleSelect,
//             isRequired: true,
//             orderIndex: 3,
//             options: [
//               { optionId: "opt-rob-low", fieldId: "field_risk_of_bias", value: "Low", displayOrder: 1 },
//               { optionId: "opt-rob-some", fieldId: "field_risk_of_bias", value: "Some concerns", displayOrder: 2 },
//               { optionId: "opt-rob-high", fieldId: "field_risk_of_bias", value: "High", displayOrder: 3 },
//             ],
//             subFields: [],
//           },
//           {
//             fieldId: "field_outcome_categories",
//             templateId: MOCK_TEMPLATE_ID,
//             parentFieldId: "field_outcomes_group",
//             name: "Outcome Categories",
//             instruction: "Select all relevant categories",
//             fieldType: FieldTypeEnum.MultiSelect,
//             isRequired: false,
//             orderIndex: 4,
//             options: [
//               { optionId: "opt-cat-performance", fieldId: "field_outcome_categories", value: "Performance", displayOrder: 1 },
//               { optionId: "opt-cat-accuracy", fieldId: "field_outcome_categories", value: "Accuracy", displayOrder: 2 },
//               { optionId: "opt-cat-usability", fieldId: "field_outcome_categories", value: "Usability", displayOrder: 3 },
//             ],
//             subFields: [],
//           },
//         ],
//       },
//     ],
//   },
// ];

// export function createMockExtractionRecords(): Record<string, ExtractionPaperRecord> {
//   return {
//     // ── paper-001: in-progress — reviewer-a has a partial draft ──────────────
//     "paper-001": {
//       paperId: "paper-001",
//       assigneeId: "reviewer-a",
//       assigneeName: "Reviewer A (Simulation)",
//       status: "in-progress",
//       draftsByReviewer: {
//         "reviewer-a": {
//           field_sample_size: 120,
//           field_study_design: "RCT",
//           field_followup_months: 6,
//           field_age_mean: 35.2,
//           field_female_percent: 48.5,
//           field_intervention_type: "Software Tool",
//           field_dosage_description:
//             "Web-based screening assistant, 2 sessions per week over 8 weeks.",
//         },
//       },
//       submissions: [],
//       finalValues: {},
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },

//     // ── paper-002: awaiting-consensus — two submissions, two conflicts ────────
//     "paper-002": {
//       paperId: "paper-002",
//       assigneeId: "reviewer-b",
//       assigneeName: "Reviewer B (Simulation)",
//       status: "awaiting-consensus",
//       draftsByReviewer: {
//         "reviewer-a": {
//           field_sample_size: 96,
//           field_study_design: "Cohort",
//           field_followup_months: 12,
//           field_age_mean: 31.4,
//           field_female_percent: 52.0,
//           field_intervention_type: "Training Program",
//           field_dosage_description: "1-day workshop + 3-week online module.",
//           field_primary_outcome: "Improved extraction consistency",
//           field_adverse_events: false,
//           field_risk_of_bias: "Low",
//           field_outcome_categories: ["Performance", "Usability"],
//         },
//         "reviewer-b": {
//           field_sample_size: 102,
//           field_study_design: "Cohort",
//           field_followup_months: 12,
//           field_age_mean: 31.4,
//           field_female_percent: 52.0,
//           field_intervention_type: "Training Program",
//           field_dosage_description: "1-day workshop + 3-week online module.",
//           field_primary_outcome: "Improved extraction consistency",
//           field_adverse_events: false,
//           field_risk_of_bias: "Some concerns",
//           field_outcome_categories: ["Performance", "Usability"],
//         },
//       },
//       submissions: [
//         {
//           reviewerId: "reviewer-a",
//           reviewerName: "Reviewer A (Simulation)",
//           submittedAt: NOW,
//           values: {
//             field_sample_size: 96,
//             field_study_design: "Cohort",
//             field_primary_outcome: "Improved extraction consistency",
//             field_adverse_events: false,
//             field_risk_of_bias: "Low",
//             field_outcome_categories: ["Performance", "Usability"],
//           },
//         },
//         {
//           reviewerId: "reviewer-b",
//           reviewerName: "Reviewer B (Simulation)",
//           submittedAt: NOW,
//           values: {
//             field_sample_size: 102,
//             field_study_design: "Cohort",
//             field_primary_outcome: "Improved extraction consistency",
//             field_adverse_events: false,
//             field_risk_of_bias: "Some concerns",
//             field_outcome_categories: ["Performance", "Usability"],
//           },
//         },
//       ],
//       finalValues: {},
//       conflictFieldIds: ["field_sample_size", "field_risk_of_bias"],
//       updatedAt: NOW,
//     },

//     // ── paper-003: completed — fully adjudicated ───────────────────────────────
//     "paper-003": {
//       paperId: "paper-003",
//       assigneeId: "reviewer-a",
//       assigneeName: "Reviewer A (Simulation)",
//       status: "completed",
//       draftsByReviewer: {
//         "reviewer-a": {
//           field_sample_size: 88,
//           field_study_design: "Case-Control",
//           field_followup_months: 24,
//           field_age_mean: 44.7,
//           field_female_percent: 39.0,
//           field_intervention_type: "Process Change",
//           field_dosage_description: "Sequential dual-reviewer adjudication protocol.",
//           field_primary_outcome: "Reduced screening time",
//           field_adverse_events: false,
//           field_risk_of_bias: "Low",
//           field_outcome_categories: ["Performance", "Accuracy"],
//         },
//       },
//       submissions: [
//         {
//           reviewerId: "reviewer-a",
//           reviewerName: "Reviewer A (Simulation)",
//           submittedAt: NOW,
//           values: {
//             field_sample_size: 88,
//             field_study_design: "Case-Control",
//             field_primary_outcome: "Reduced screening time",
//             field_adverse_events: false,
//             field_risk_of_bias: "Low",
//             field_outcome_categories: ["Performance", "Accuracy"],
//           },
//         },
//       ],
//       finalValues: {
//         field_sample_size: 88,
//         field_study_design: "Case-Control",
//         field_followup_months: 24,
//         field_age_mean: 44.7,
//         field_female_percent: 39.0,
//         field_intervention_type: "Process Change",
//         field_dosage_description: "Sequential dual-reviewer adjudication protocol.",
//         field_primary_outcome: "Reduced screening time",
//         field_adverse_events: false,
//         field_risk_of_bias: "Low",
//         field_outcome_categories: ["Performance", "Accuracy"],
//       },
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },

//     // ── paper-006: todo — unassigned, no activity yet ─────────────────────────
//     "paper-006": {
//       paperId: "paper-006",
//       assigneeId: null,
//       assigneeName: null,
//       status: "todo",
//       draftsByReviewer: {},
//       submissions: [],
//       finalValues: {},
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },

//     // ── paper-007: todo — assigned but not started ────────────────────────────
//     "paper-007": {
//       paperId: "paper-007",
//       assigneeId: "reviewer-b",
//       assigneeName: "Reviewer B (Simulation)",
//       status: "todo",
//       draftsByReviewer: {},
//       submissions: [],
//       finalValues: {},
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },

//     // ── paper-008: in-progress — reviewer-a has started but not finished ─────
//     "paper-008": {
//       paperId: "paper-008",
//       assigneeId: "reviewer-a",
//       assigneeName: "Reviewer A (Simulation)",
//       status: "in-progress",
//       draftsByReviewer: {
//         "reviewer-a": {
//           field_sample_size: 142,
//           field_study_design: "Cohort",
//           field_age_mean: 28.9,
//           field_primary_outcome:
//             "Improved SLR tool adoption and usability satisfaction",
//         },
//       },
//       submissions: [],
//       finalValues: {},
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },

//     // ── paper-009: in-progress — reviewer-b has a full draft saved ───────────
//     "paper-009": {
//       paperId: "paper-009",
//       assigneeId: "reviewer-b",
//       assigneeName: "Reviewer B (Simulation)",
//       status: "in-progress",
//       draftsByReviewer: {
//         "reviewer-b": {
//           field_sample_size: 34,
//           field_study_design: "Case-Control",
//           field_followup_months: null,
//           field_age_mean: null,
//           field_female_percent: null,
//           field_intervention_type: "Process Change",
//           field_dosage_description:
//             "Multi-database search strategy comparison over 34 previously published SLRs.",
//           field_primary_outcome: "Reduced publication bias risk",
//           field_adverse_events: false,
//           field_risk_of_bias: "Some concerns",
//           field_outcome_categories: ["Accuracy"],
//         },
//       },
//       submissions: [],
//       finalValues: {},
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },

//     // ── paper-010: awaiting-consensus — one conflict on sample size ───────────
//     "paper-010": {
//       paperId: "paper-010",
//       assigneeId: "reviewer-a",
//       assigneeName: "Reviewer A (Simulation)",
//       status: "awaiting-consensus",
//       draftsByReviewer: {
//         "reviewer-a": {
//           field_sample_size: 60,
//           field_study_design: "RCT",
//           field_followup_months: 3,
//           field_age_mean: 33.1,
//           field_female_percent: 45.0,
//           field_intervention_type: "Software Tool",
//           field_dosage_description: "Three-platform parallel extraction study, 2-week period.",
//           field_primary_outcome: "Extraction accuracy kappa",
//           field_adverse_events: false,
//           field_risk_of_bias: "Low",
//           field_outcome_categories: ["Accuracy", "Usability"],
//         },
//         "reviewer-b": {
//           field_sample_size: 58,
//           field_study_design: "RCT",
//           field_followup_months: 3,
//           field_age_mean: 33.1,
//           field_female_percent: 45.0,
//           field_intervention_type: "Software Tool",
//           field_dosage_description: "Three-platform parallel extraction study, 2-week period.",
//           field_primary_outcome: "Extraction accuracy kappa",
//           field_adverse_events: false,
//           field_risk_of_bias: "Low",
//           field_outcome_categories: ["Accuracy", "Usability"],
//         },
//       },
//       submissions: [
//         {
//           reviewerId: "reviewer-a",
//           reviewerName: "Reviewer A (Simulation)",
//           submittedAt: NOW,
//           values: {
//             field_sample_size: 60,
//             field_study_design: "RCT",
//             field_primary_outcome: "Extraction accuracy kappa",
//             field_adverse_events: false,
//             field_risk_of_bias: "Low",
//             field_outcome_categories: ["Accuracy", "Usability"],
//           },
//         },
//         {
//           reviewerId: "reviewer-b",
//           reviewerName: "Reviewer B (Simulation)",
//           submittedAt: NOW,
//           values: {
//             field_sample_size: 58,
//             field_study_design: "RCT",
//             field_primary_outcome: "Extraction accuracy kappa",
//             field_adverse_events: false,
//             field_risk_of_bias: "Low",
//             field_outcome_categories: ["Accuracy", "Usability"],
//           },
//         },
//       ],
//       finalValues: {},
//       conflictFieldIds: ["field_sample_size"],
//       updatedAt: NOW,
//     },

//     // ── paper-011: completed — fully resolved and finalized ───────────────────
//     "paper-011": {
//       paperId: "paper-011",
//       assigneeId: "reviewer-b",
//       assigneeName: "Reviewer B (Simulation)",
//       status: "completed",
//       draftsByReviewer: {
//         "reviewer-b": {
//           field_sample_size: 80,
//           field_study_design: "RCT",
//           field_followup_months: 6,
//           field_age_mean: 38.5,
//           field_female_percent: 43.75,
//           field_intervention_type: "Process Change",
//           field_dosage_description: "Three extraction form variants compared within-subjects.",
//           field_primary_outcome: "Inter-rater agreement (kappa)",
//           field_adverse_events: false,
//           field_risk_of_bias: "Low",
//           field_outcome_categories: ["Accuracy", "Performance"],
//         },
//       },
//       submissions: [
//         {
//           reviewerId: "reviewer-b",
//           reviewerName: "Reviewer B (Simulation)",
//           submittedAt: NOW,
//           values: {
//             field_sample_size: 80,
//             field_study_design: "RCT",
//             field_primary_outcome: "Inter-rater agreement (kappa)",
//             field_adverse_events: false,
//             field_risk_of_bias: "Low",
//             field_outcome_categories: ["Accuracy", "Performance"],
//           },
//         },
//       ],
//       finalValues: {
//         field_sample_size: 80,
//         field_study_design: "RCT",
//         field_followup_months: 6,
//         field_age_mean: 38.5,
//         field_female_percent: 43.75,
//         field_intervention_type: "Process Change",
//         field_dosage_description: "Three extraction form variants compared within-subjects.",
//         field_primary_outcome: "Inter-rater agreement (kappa)",
//         field_adverse_events: false,
//         field_risk_of_bias: "Low",
//         field_outcome_categories: ["Accuracy", "Performance"],
//       },
//       conflictFieldIds: [],
//       updatedAt: NOW,
//     },
//   };
// }